marcoeilers/nagini

src/nagini_translation/analyzer.py, src/nagini_translation/lib/errors/wrappers.py, src/nagini_translation/lib/program_nodes.py, src/nagini_translation/lib/viper_ast.py, src/nagini_translation/main.py, src/nagini_translation/resources/preamble.index, src/nagini_translation/translators/common.py, src/nagini_translation/translators/contract.py, src/nagini_translation/translators/obligation/method_node.py, src/nagini_translation/translators/program.py, src/nagini_translation/translators/statement.py, src/nagini_translation/verifier.py, tests/functional/translation/issues/00111.py, tests/functional/verification/issues/00112.py, tests/functional/verification/issues/00113.py, tests/functional/verification/issues/00115.py, tests/functional/verification/test_assign.py, tests/obligations/verification/test_builtin_must_terminate.py
Fixes for a number of small issues (and regression tests for others):
- Error reporting for obligations in builtin methods improved (issue found by CAV artifact reviewer)
- Command line option for more detailed, Viper-level error messages added
- Problem with for loop fixed (issue found by Sascha)
- Test cases added for the above, as well as a problem with global variables that I couldn't fix yet (found by Fabio)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcoeilers/nagini/116)
=> Small fixes and improvements

src/nagini_translation/translators/call.py, tests/functional/verification/issues/00117.py
This is the pull request regarding issue 117. Additionally to the test case added from the issue report, other 3 test cases were added to fully exercise all possible inputs the modified function is expected to handle.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcoeilers/nagini/122)
=> Fixed issue 117: pure function calls on union receivers crash the verifier

src/nagini_translation/translators/common.py, src/nagini_translation/translators/expression.py, tests/functional/verification/issues/00118.py
This is fixing issue 118 with the same title. When position is not supplied to get_function_call, the node position is used.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcoeilers/nagini/123)
=> Imprecise handling of implicit type conversion with union type

src/nagini_translation/lib/viper_ast.py
This is fixing the broken build due to a change in Silver's API ('Method' node).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcoeilers/nagini/133)
=> Added support for 'cached' feature

README.rst, setup.py, src/nagini_translation/analyzer.py, src/nagini_translation/lib/errors/messages.py, src/nagini_translation/lib/resolver.py, src/nagini_translation/lib/viper_ast.py, src/nagini_translation/models/converter.py, src/nagini_translation/resources/all.sil, src/nagini_translation/sif/resources/all.sil, src/nagini_translation/translators/method.py, src/nagini_translation/verifier.py, tests/functional/verification/examples/VerifyThis22_Challenge2.py, tests/functional/verification/examples/iap_bst.py, tests/functional/verification/test_decreases.py, tests/functional/verification/test_dicts.py, tests/functional/verification/test_tuples.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcoeilers/nagini/157)
=> Version bump, decreases clauses with predicates

src/nagini_translation/analyzer.py, src/nagini_translation/lib/typeinfo.py, tests/functional/translation/test_partial_type.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcoeilers/nagini/170)
=> Proper error message for partially inferred types

src/nagini_translation/resources/preamble.index, src/nagini_translation/translators/call.py, tests/functional/verification/test_range.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcoeilers/nagini/171)
=> Supporting range() with one argument

src/nagini_translation/lib/viper_ast.py, src/nagini_translation/main.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcoeilers/nagini/175)
=> Update Viper again

src/nagini_translation/lib/errors/wrappers.py, src/nagini_translation/resources/bool.sil, src/nagini_translation/resources/list.sil, src/nagini_translation/resources/preamble.index, src/nagini_translation/resources/set_dict.sil
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcoeilers/nagini/174)
=> Better error messages for built-in functions (using Viper annotations)

src/nagini_translation/translators/call.py, tests/functional/verification/issues/00176.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcoeilers/nagini/177)
=> Fixing #176

src/nagini_translation/analyzer.py, src/nagini_translation/translators/expression.py, tests/functional/translation/issues/00185.py, tests/functional/translation/issues/00186.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcoeilers/nagini/187)
=> Fixing two issues

src/nagini_translation/lib/constants.py, src/nagini_translation/lib/program_nodes.py, src/nagini_translation/translators/statement.py, tests/functional/verification/test_inplace_operators.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcoeilers/nagini/188)
=> Add support for overloading inplace arithmetic operators

src/nagini_translation/main.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcoeilers/nagini/189)
=> Fixing program submitter call

src/nagini_translation/lib/resolver.py
Fixes crash when an unsupported operator is used.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcoeilers/nagini/195)
=> Fix unsupported operator crash

src/nagini_translation/resources/bool.sil, src/nagini_translation/resources/float.sil, src/nagini_translation/resources/float_ieee32.sil, src/nagini_translation/resources/float_real.sil, src/nagini_translation/resources/list.sil, src/nagini_translation/resources/seq.sil, src/nagini_translation/resources/tuple.sil
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcoeilers/nagini/207)
=> More annotations for precondition errors for builtin functions

.github/workflows/testWin.yml, src/nagini_translation/lib/config.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcoeilers/nagini/211)
=> Add basic Windows tests in CI; fix automatic Z3 executable path detection on Windows

src/nagini_translation/resources/bool.sil, src/nagini_translation/resources/builtins.json, src/nagini_translation/translators/expression.py, tests/functional/verification/test_builtin_functions.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcoeilers/nagini/213)
=> Basic ** operator support for integers

src/nagini_contracts/contracts.py, src/nagini_translation/analyzer.py, src/nagini_translation/lib/context.py, src/nagini_translation/lib/program_nodes.py, src/nagini_translation/sif/translators/method.py, src/nagini_translation/sif/translators/statement.py, src/nagini_translation/translators/call.py, src/nagini_translation/translators/common.py, src/nagini_translation/translators/expression.py, src/nagini_translation/translators/method.py, src/nagini_translation/translators/obligation/fork.py, src/nagini_translation/translators/obligation/inexhale.py, src/nagini_translation/translators/obligation/interface.py, src/nagini_translation/translators/obligation/loop.py, src/nagini_translation/translators/obligation/loop_node.py, src/nagini_translation/translators/obligation/method.py, src/nagini_translation/translators/obligation/obligation_info.py, src/nagini_translation/translators/obligation/waitlevel.py, src/nagini_translation/translators/program.py, src/nagini_translation/translators/statement.py, tests/functional/translation/test_inline_1.py, tests/functional/translation/test_inline_2.py, tests/functional/translation/test_inline_3.py, tests/functional/translation/test_inline_4.py, tests/functional/translation/test_inline_5.py, tests/functional/translation/test_inline_6.py, tests/functional/verification/test_inline.py, tests/functional/verification/test_super.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcoeilers/nagini/215)
=> @Inline decorator

src/nagini_translation/tests.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcoeilers/nagini/214)
=> Slightly better output for test failures

src/nagini_translation/resources/bool.sil, src/nagini_translation/resources/builtins.json, src/nagini_translation/translators/call.py, src/nagini_translation/translators/expression.py, tests/functional/verification/issues/00216.py
Adding a special case for the __pow__ operator to get good automation with constants, which was the existing implementation, and still get termination otherwise.
Fixes #216.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcoeilers/nagini/217)
=> Better __pow__ implementation

src/nagini_translation/resources/builtins.json, tests/functional/verification/issues/00218.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcoeilers/nagini/220)
=> Fix crash from issue #218

src/nagini_translation/lib/resolver.py, tests/functional/verification/test_tuples.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcoeilers/nagini/227)
=> Fix crash on dynamically indexed tuple

src/nagini_translation/translators/program.py, tests/functional/translation/issues/00185.py, tests/functional/translation/issues/00186.py, tests/functional/translation/issues/00235.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcoeilers/nagini/236)
=> Translating fields before properties to fix #235

src/nagini_translation/translators/contract.py, tests/functional/translation/issues/00238.py
Fixes #238
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcoeilers/nagini/239)
=> Allowing builtin predicates and MayCreate only in pure positions
